# Generated by Django 2.0.7 on 2018-07-27 13:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('isDelete', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=20, null=True)),
                ('lastime', models.DateTimeField(auto_now=True, null=True)),
                ('creatime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'article',
            },
            managers=[
                ('article', django.db.models.manager.Manager()),
            ],
        ),
    ]
