# Generated by Django 2.0.7 on 2018-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=20, null=True)),
                ('emil', models.EmailField(max_length=254, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
