# Generated by Django 2.0.7 on 2018-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/picture'),
        ),
    ]
