# Generated by Django 2.0.7 on 2018-07-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20180728_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
