# Generated by Django 2.0.7 on 2018-07-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_message_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True)),
                ('commenter', models.CharField(max_length=20, null=True)),
                ('emil', models.EmailField(max_length=254, null=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Article')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
