# Generated by Django 2.0.7 on 2018-07-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='phone',
        ),
    ]
