# Generated by Django 2.0.7 on 2018-07-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_comment_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
    ]
