# Generated by Django 2.0.7 on 2018-07-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20180729_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
