# Generated by Django 2.0.7 on 2018-08-02 15:17

from django.db import migrations
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20180729_2228'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('message', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
