# Generated by Django 2.0.7 on 2018-08-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20180803_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'log',
                'ordering': ['-id'],
            },
        ),
    ]
