# Generated by Django 2.0.7 on 2018-08-03 04:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_log'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='log',
            managers=[
                ('log', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='commenter',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
